using System.Text.Json.Serialization;

namespace TestSuite.Coordinator;

public class PullRequestEvent
{
    [JsonPropertyName("number")]
    public int Number { get; set; }

    [JsonPropertyName("action")]
    public string Action { get; set; }

    [JsonPropertyName("pull_request")]
    public PullRequestDescriptor PullRequest { get; set; }

    [JsonPropertyName("repository")]
    public RepositoryDescriptor Repository { get; set; }

    public class BranchDescriptor
    {
        [JsonPropertyName("ref")]
        public string Ref { get; set; }
    }

    public class PullRequestDescriptor
    {
        [JsonPropertyName("title")]
        public string Title { get; set; }
        [JsonPropertyName("draft")]
        public bool IsDraft { get; set; }
        [JsonPropertyName("head")]
        public BranchDescriptor Head { get; set; }
    }

    public class RepositoryDescriptor
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [JsonPropertyName("full_name")]
        public string FullName { get; set; }
        [JsonPropertyName("clone_url")]
        public string CloneUrl { get; set; }
    }
    /*
    {
  "action": "opened",
  "number": 452,
  "pull_request": {
    "url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/452",
    "id": 1759893261,
    "node_id": "PR_kwDOCGgm1s5o5dcN",
    "html_url": "https://github.com/WildernessLabs/Meadow.Core/pull/452",
    "diff_url": "https://github.com/WildernessLabs/Meadow.Core/pull/452.diff",
    "patch_url": "https://github.com/WildernessLabs/Meadow.Core/pull/452.patch",
    "issue_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/452",
    "number": 452,
    "state": "open",
    "locked": false,
    "title": "TEST PR: IGNORE ME!",
    "user": {
      "login": "ctacke",
      "id": 5286930,
      "node_id": "MDQ6VXNlcjUyODY5MzA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5286930?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ctacke",
      "html_url": "https://github.com/ctacke",
      "followers_url": "https://api.github.com/users/ctacke/followers",
      "following_url": "https://api.github.com/users/ctacke/following{/other_user}",
      "gists_url": "https://api.github.com/users/ctacke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ctacke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ctacke/subscriptions",
      "organizations_url": "https://api.github.com/users/ctacke/orgs",
      "repos_url": "https://api.github.com/users/ctacke/repos",
      "events_url": "https://api.github.com/users/ctacke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ctacke/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": null,
    "created_at": "2024-03-06T22:57:50Z",
    "updated_at": "2024-03-06T22:57:50Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "assignees": [],
    "requested_reviewers": [],
    "requested_teams": [],
    "labels": [],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/452/commits",
    "review_comments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/452/comments",
    "review_comment_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/452/comments",
    "statuses_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/statuses/3cd29199f163f3ee41dd49d98fcab6314696671c",
    "head": {
      "label": "WildernessLabs:feature/crash-reporting",
      "ref": "feature/crash-reporting",
      "sha": "3cd29199f163f3ee41dd49d98fcab6314696671c",
      "user": {
        "login": "WildernessLabs",
        "id": 22922015,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyOTIyMDE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/22922015?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/WildernessLabs",
        "html_url": "https://github.com/WildernessLabs",
        "followers_url": "https://api.github.com/users/WildernessLabs/followers",
        "following_url": "https://api.github.com/users/WildernessLabs/following{/other_user}",
        "gists_url": "https://api.github.com/users/WildernessLabs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/WildernessLabs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/WildernessLabs/subscriptions",
        "organizations_url": "https://api.github.com/users/WildernessLabs/orgs",
        "repos_url": "https://api.github.com/users/WildernessLabs/repos",
        "events_url": "https://api.github.com/users/WildernessLabs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/WildernessLabs/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 141043414,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNDEwNDM0MTQ=",
        "name": "Meadow.Core",
        "full_name": "WildernessLabs/Meadow.Core",
        "private": false,
        "owner": {
          "login": "WildernessLabs",
          "id": 22922015,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyOTIyMDE1",
          "avatar_url": "https://avatars.githubusercontent.com/u/22922015?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/WildernessLabs",
          "html_url": "https://github.com/WildernessLabs",
          "followers_url": "https://api.github.com/users/WildernessLabs/followers",
          "following_url": "https://api.github.com/users/WildernessLabs/following{/other_user}",
          "gists_url": "https://api.github.com/users/WildernessLabs/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/WildernessLabs/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/WildernessLabs/subscriptions",
          "organizations_url": "https://api.github.com/users/WildernessLabs/orgs",
          "repos_url": "https://api.github.com/users/WildernessLabs/repos",
          "events_url": "https://api.github.com/users/WildernessLabs/events{/privacy}",
          "received_events_url": "https://api.github.com/users/WildernessLabs/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/WildernessLabs/Meadow.Core",
        "description": "Meadow BCL",
        "fork": false,
        "url": "https://api.github.com/repos/WildernessLabs/Meadow.Core",
        "forks_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/forks",
        "keys_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/teams",
        "hooks_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/hooks",
        "issue_events_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/events{/number}",
        "events_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/events",
        "assignees_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/assignees{/user}",
        "branches_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/branches{/branch}",
        "tags_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/tags",
        "blobs_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/languages",
        "stargazers_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/stargazers",
        "contributors_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/contributors",
        "subscribers_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/subscribers",
        "subscription_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/subscription",
        "commits_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/contents/{+path}",
        "compare_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/merges",
        "archive_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/downloads",
        "issues_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues{/number}",
        "pulls_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/labels{/name}",
        "releases_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/releases{/id}",
        "deployments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/deployments",
        "created_at": "2018-07-15T16:59:05Z",
        "updated_at": "2024-03-03T18:37:40Z",
        "pushed_at": "2024-03-06T22:57:50Z",
        "git_url": "git://github.com/WildernessLabs/Meadow.Core.git",
        "ssh_url": "git@github.com:WildernessLabs/Meadow.Core.git",
        "clone_url": "https://github.com/WildernessLabs/Meadow.Core.git",
        "svn_url": "https://github.com/WildernessLabs/Meadow.Core",
        "homepage": "https://www.wildernesslabs.co",
        "size": 7890,
        "stargazers_count": 24,
        "watchers_count": 24,
        "language": "C#",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 7,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 10,
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "csharp",
          "dotnet",
          "embedded",
          "hardware",
          "iot",
          "meadow"
        ],
        "visibility": "public",
        "forks": 7,
        "open_issues": 10,
        "watchers": 24,
        "default_branch": "develop",
        "allow_squash_merge": false,
        "allow_merge_commit": true,
        "allow_rebase_merge": false,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "base": {
      "label": "WildernessLabs:develop",
      "ref": "develop",
      "sha": "461496bcef1ebbfb847a0fa1f91ccf7576ac90b3",
      "user": {
        "login": "WildernessLabs",
        "id": 22922015,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyOTIyMDE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/22922015?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/WildernessLabs",
        "html_url": "https://github.com/WildernessLabs",
        "followers_url": "https://api.github.com/users/WildernessLabs/followers",
        "following_url": "https://api.github.com/users/WildernessLabs/following{/other_user}",
        "gists_url": "https://api.github.com/users/WildernessLabs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/WildernessLabs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/WildernessLabs/subscriptions",
        "organizations_url": "https://api.github.com/users/WildernessLabs/orgs",
        "repos_url": "https://api.github.com/users/WildernessLabs/repos",
        "events_url": "https://api.github.com/users/WildernessLabs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/WildernessLabs/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 141043414,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNDEwNDM0MTQ=",
        "name": "Meadow.Core",
        "full_name": "WildernessLabs/Meadow.Core",
        "private": false,
        "owner": {
          "login": "WildernessLabs",
          "id": 22922015,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyOTIyMDE1",
          "avatar_url": "https://avatars.githubusercontent.com/u/22922015?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/WildernessLabs",
          "html_url": "https://github.com/WildernessLabs",
          "followers_url": "https://api.github.com/users/WildernessLabs/followers",
          "following_url": "https://api.github.com/users/WildernessLabs/following{/other_user}",
          "gists_url": "https://api.github.com/users/WildernessLabs/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/WildernessLabs/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/WildernessLabs/subscriptions",
          "organizations_url": "https://api.github.com/users/WildernessLabs/orgs",
          "repos_url": "https://api.github.com/users/WildernessLabs/repos",
          "events_url": "https://api.github.com/users/WildernessLabs/events{/privacy}",
          "received_events_url": "https://api.github.com/users/WildernessLabs/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/WildernessLabs/Meadow.Core",
        "description": "Meadow BCL",
        "fork": false,
        "url": "https://api.github.com/repos/WildernessLabs/Meadow.Core",
        "forks_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/forks",
        "keys_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/teams",
        "hooks_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/hooks",
        "issue_events_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/events{/number}",
        "events_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/events",
        "assignees_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/assignees{/user}",
        "branches_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/branches{/branch}",
        "tags_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/tags",
        "blobs_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/languages",
        "stargazers_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/stargazers",
        "contributors_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/contributors",
        "subscribers_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/subscribers",
        "subscription_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/subscription",
        "commits_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/contents/{+path}",
        "compare_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/merges",
        "archive_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/downloads",
        "issues_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues{/number}",
        "pulls_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/labels{/name}",
        "releases_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/releases{/id}",
        "deployments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/deployments",
        "created_at": "2018-07-15T16:59:05Z",
        "updated_at": "2024-03-03T18:37:40Z",
        "pushed_at": "2024-03-06T22:57:50Z",
        "git_url": "git://github.com/WildernessLabs/Meadow.Core.git",
        "ssh_url": "git@github.com:WildernessLabs/Meadow.Core.git",
        "clone_url": "https://github.com/WildernessLabs/Meadow.Core.git",
        "svn_url": "https://github.com/WildernessLabs/Meadow.Core",
        "homepage": "https://www.wildernesslabs.co",
        "size": 7890,
        "stargazers_count": 24,
        "watchers_count": 24,
        "language": "C#",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 7,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 10,
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "csharp",
          "dotnet",
          "embedded",
          "hardware",
          "iot",
          "meadow"
        ],
        "visibility": "public",
        "forks": 7,
        "open_issues": 10,
        "watchers": 24,
        "default_branch": "develop",
        "allow_squash_merge": false,
        "allow_merge_commit": true,
        "allow_rebase_merge": false,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/452"
      },
      "html": {
        "href": "https://github.com/WildernessLabs/Meadow.Core/pull/452"
      },
      "issue": {
        "href": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/452"
      },
      "comments": {
        "href": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/452/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/452/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls/452/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/WildernessLabs/Meadow.Core/statuses/3cd29199f163f3ee41dd49d98fcab6314696671c"
      }
    },
    "author_association": "CONTRIBUTOR",
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": false,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "unknown",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 216,
    "deletions": 1,
    "changed_files": 3
  },
  "repository": {
    "id": 141043414,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNDEwNDM0MTQ=",
    "name": "Meadow.Core",
    "full_name": "WildernessLabs/Meadow.Core",
    "private": false,
    "owner": {
      "login": "WildernessLabs",
      "id": 22922015,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyOTIyMDE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/22922015?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WildernessLabs",
      "html_url": "https://github.com/WildernessLabs",
      "followers_url": "https://api.github.com/users/WildernessLabs/followers",
      "following_url": "https://api.github.com/users/WildernessLabs/following{/other_user}",
      "gists_url": "https://api.github.com/users/WildernessLabs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WildernessLabs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WildernessLabs/subscriptions",
      "organizations_url": "https://api.github.com/users/WildernessLabs/orgs",
      "repos_url": "https://api.github.com/users/WildernessLabs/repos",
      "events_url": "https://api.github.com/users/WildernessLabs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WildernessLabs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/WildernessLabs/Meadow.Core",
    "description": "Meadow BCL",
    "fork": false,
    "url": "https://api.github.com/repos/WildernessLabs/Meadow.Core",
    "forks_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/forks",
    "keys_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/teams",
    "hooks_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/hooks",
    "issue_events_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/events{/number}",
    "events_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/events",
    "assignees_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/assignees{/user}",
    "branches_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/branches{/branch}",
    "tags_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/tags",
    "blobs_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/languages",
    "stargazers_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/stargazers",
    "contributors_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/contributors",
    "subscribers_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/subscribers",
    "subscription_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/subscription",
    "commits_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/contents/{+path}",
    "compare_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/merges",
    "archive_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/downloads",
    "issues_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/issues{/number}",
    "pulls_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/labels{/name}",
    "releases_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/releases{/id}",
    "deployments_url": "https://api.github.com/repos/WildernessLabs/Meadow.Core/deployments",
    "created_at": "2018-07-15T16:59:05Z",
    "updated_at": "2024-03-03T18:37:40Z",
    "pushed_at": "2024-03-06T22:57:50Z",
    "git_url": "git://github.com/WildernessLabs/Meadow.Core.git",
    "ssh_url": "git@github.com:WildernessLabs/Meadow.Core.git",
    "clone_url": "https://github.com/WildernessLabs/Meadow.Core.git",
    "svn_url": "https://github.com/WildernessLabs/Meadow.Core",
    "homepage": "https://www.wildernesslabs.co",
    "size": 7890,
    "stargazers_count": 24,
    "watchers_count": 24,
    "language": "C#",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 7,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 10,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "csharp",
      "dotnet",
      "embedded",
      "hardware",
      "iot",
      "meadow"
    ],
    "visibility": "public",
    "forks": 7,
    "open_issues": 10,
    "watchers": 24,
    "default_branch": "develop",
    "custom_properties": {}
  },
  "organization": {
    "login": "WildernessLabs",
    "id": 22922015,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyOTIyMDE1",
    "url": "https://api.github.com/orgs/WildernessLabs",
    "repos_url": "https://api.github.com/orgs/WildernessLabs/repos",
    "events_url": "https://api.github.com/orgs/WildernessLabs/events",
    "hooks_url": "https://api.github.com/orgs/WildernessLabs/hooks",
    "issues_url": "https://api.github.com/orgs/WildernessLabs/issues",
    "members_url": "https://api.github.com/orgs/WildernessLabs/members{/member}",
    "public_members_url": "https://api.github.com/orgs/WildernessLabs/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/22922015?v=4",
    "description": ""
  },
  "sender": {
    "login": "ctacke",
    "id": 5286930,
    "node_id": "MDQ6VXNlcjUyODY5MzA=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5286930?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ctacke",
    "html_url": "https://github.com/ctacke",
    "followers_url": "https://api.github.com/users/ctacke/followers",
    "following_url": "https://api.github.com/users/ctacke/following{/other_user}",
    "gists_url": "https://api.github.com/users/ctacke/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ctacke/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ctacke/subscriptions",
    "organizations_url": "https://api.github.com/users/ctacke/orgs",
    "repos_url": "https://api.github.com/users/ctacke/repos",
    "events_url": "https://api.github.com/users/ctacke/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ctacke/received_events",
    "type": "User",
    "site_admin": false
  }
}
    */

}
