name: Meadow.TestSuite

on: 
  repository_dispatch:
    types: [meadow_core_build]
  push:
    branches:
      - main, develop

jobs:
  run_if_meadow_core_build:
    if: ${{ github.event.meadow_core_payload.built }}
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --mac=8.2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: msbuild Meadow.TestSuite.sln /t:Restore

    - name: Build Meadow.Core
      run: msbuild Meadow.TestSuite.sln /t:Build /p:Configuration=Release